stages:
 features:
   cmd: python src/feature_selection.py
   deps:
     - data/raw/train.csv
     - src/feature_selection.py
   outs:
     - data/features/train.csv
 prepared:
   cmd: python src/prepare.py
   deps:
     - data/features/train.csv
     - src/prepare.py
   outs:
     - data/prepared/train.csv
 train_model:
   cmd: python src/train_model.py
   deps:
     - data/prepared/train.csv
     - src/train_model.py
   outs:
     - model/model.pkl

